[package]
name = "voter-define"
version = "0.2.0"
edition = "2021"
resolver = "2"

[dependencies]
casper-contract = "=5.1.1"
casper-types = "6.0.1"
base64ct = "<1.8.0"

[[bin]]
name = "voter-define"
path = "src/main.rs"
bench = false
doctest = false
test = false
